#!/usr/bin/env bash
# this bash script changes localhost address to 127.0.0.2

cp /etc/hosts /etc/hosts.bak
sed '/localhost/d' /etc/hosts.bak > /etc/hosts
echo '127.0.0.2       localhost' >> /etc/hosts
echo '8.8.8.8       facebook.com' >> /etc/hosts
